AllCops:
  Exclude:
    - '*.gemspec'

Style/StringLiterals:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 15
